# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "go-mod-outdated-${version}";
  version = "v0.7.0";
  rev = "9f051566d56958856a2da27588dfcb7ffbecaef0";

  goPackagePath = "github.com/psampaz/go-mod-outdated";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/psampaz/go-mod-outdated";
    sha256 = "067q0j1v9qiil3n2jr5qz19lss11083ksqaq9sabxa9rs2572hny";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = ''
      Find outdated dependencies of your Go projects. go-mod-outdated provides a table view of
      the go list -u -m -json all command which lists all dependencies of a Go project and their
      available minor and patch updates. It also provides a way to filter indirect dependencies
      and dependencies without updates.
    '';
    homepage = "https://github.com/psampaz/go-mod-outdated";
    license = licenses.mit;
    platforms = platforms.unix;
    maintainers = with lib.maintainers; [ wiedzmin ];
  };
}
