# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/rogpeppe/go-internal";
    fetch = {
      type = "git";
      url = "https://github.com/rogpeppe/go-internal";
      rev = "9f985d550aa78beac49932267fd004b19fe7f270";
      sha256 = "051v81ya2rl2zvm23yjc4a1k1srmjfhmlig88hqghnxx0lrq40mp";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "cf7a54d0667139c6af74289db4164ae0b11e7b26";
      sha256 = "1r9phdf2n33c0ixzml2wdyk8cvlbdzlynl138qbld9r4914gb7da";
    };
  }
  {
    goPackagePath = "gopkg.in/errgo.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/errgo.v2";
      rev = "f768c5ab0476c50e978b039312180859c10fe8c0";
      sha256 = "065mbihiy7q67wnql0bzl9y1kkvck5ivra68254zbih52jxwrgr2";
    };
  }
]
